Vertical Candidate List=False
WheelForPaging=True
Font="Maple Mono NF CN 10"
MenuFont="Maple Mono NF CN 10"
TrayFont="Maple Mono NF CN 10"
UseInputMethodLanguageToDisplayText=True
Theme=noctalia
DarkTheme=noctalia
UseDarkTheme=True
UseAccentColor=False
EnableFractionalScale=True

